### PR TITLE
Fix Windows build

### LINKED ISSUE #394: Syntax Error with VS2019 in several headers
**Describe the bug**
Sophus is not building under Windows 10 MSVC2019 with the following cmake command:

```c
cmake .. -DSOPHUS_USE_BASIC_LOGGING=ON -DBUILD_SOPHUS_TESTS=ON -DBUILD_SOPHUS_EXAMPLES=ON
```

due to the following error:

```c
error C2059: syntax error: ')'
```

in several files, among these files:

```c
interpolate.hpp(30,1)
so3.hpp(725,1)
geometry.hpp(71,1)
...
```

**To Reproduce**

1. Use Windows 10, install MSVC2019
2. Clone this repo
3. Build with above cmake command

**Expected behavior**

It should build without error.

**Sophus version: commit hash**

Latest commit: 8e1941677ef214aab0397608f42b18fbe1a19885

**Additional context**

Seems to be related to SOPHUS_ENSURE(...)

Edit: 0422cad3d65f4cfb27014286e1a630e774c9d218 seems to be working fine.

### PR DESCRIPTION
**Pull request by nachovizzo**
And other probably too... since the original change (introduced in #376) does not work. 

As an example :

```cpp
#define SOPHUS_FMT_ARG(arg)

#else  // !SOPHUS_USE_BASIC_LOGGING
```

But later is fixed, thus, only works when using fmt:
```cpp
#if FMT_VERSION >= 90000
#define SOPHUS_FMT_ARG(arg) fmt::streamed(arg)
#else
#define SOPHUS_FMT_ARG(arg) arg
#endif
```

This PR fixes #394 and #436

### CODE REVIEW

**Comment by nachovizzo** [comment]
Closing this due to lack of activity :) feel free to reopen if needed
