### ISSUE TITLE
Won't compile with ubuntu 19.10 plus the fix

### ISSUE THREAD

**Issue by dougrm** [strasdat/Sophus#240]
Compiling in ubuntu 19.10 with it's recent g++ results in compilation errors due to various Map<Sophus-classes> having an explicit operator= and an implicit copy constructor (g++ now warns of this deprecated scenario).  The problem is that various Sophus classes have the line:

EIGEN_INHERIT_ASSIGNMENT_EQUAL_OPERATOR(Map);

This type of problem seems to have been addressed in Eigen's Master repository (but not in 3.3.7) by changing the macro:

EIGEN_INHERIT_ASSIGNMENT_OPERATORS(Map);

to inherit both operator= and copy constructor.  You could then call this macro instead of the one you do and things work.  Unfortunately, the new macro is "new", so to work with old Eigen's you need to replace every occurrence of the bad line with:

EIGEN_INHERIT_ASSIGNMENT_EQUAL_OPERATOR(Map);
EIGEN_DEFAULT_COPY_CONSTRUCTOR(Map);
 
or something equivalent. Making the changes, everything compiles. Without the changes, here is what happens:

$ cmake ..
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "3.3.0") 
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.3.7 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
-- Detected gflags version: 2.2.2
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.14.0 installed in: /usr with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.3.7 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
-- Detected gflags version: 2.2.2
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.14.0 installed in: /usr with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
-- CERES found
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.3.7 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
-- Detected gflags version: 2.2.2
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.14.0 installed in: /usr with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/sda11/data/Sophus/build
doug@eight:/mnt/sda11/data/Sophus/build$ make
Scanning dependencies of target test_rxso2
[  3%] Building CXX object test/core/CMakeFiles/test_rxso2.dir/test_rxso2.cpp.o
/mnt/sda11/data/Sophus/test/core/test_rxso2.cpp: In instantiation of ‘bool Sophus::Tests<Scalar>::testRawDataAcces() [with Scalar = double]’:
/mnt/sda11/data/Sophus/test/core/test_rxso2.cpp:92:15:   required from ‘void Sophus::Tests<Scalar>::runAll() [with Scalar = double]’
/mnt/sda11/data/Sophus/test/core/test_rxso2.cpp:228:26:   required from here
/mnt/sda11/data/Sophus/test/core/test_rxso2.cpp:135:27: error: implicitly-declared ‘Eigen::Map<Sophus::RxSO2<double> >::Map(const Eigen::Map<Sophus::RxSO2<double> >&)’ is deprecated [-Werror=deprecated-copy]
  135 |     Eigen::Map<RxSO2Type> shallow_copy = map_of_rxso2;
      |                           ^~~~~~~~~~~~
In file included from /usr/include/eigen3/Eigen/Core:88,
                 from /usr/include/eigen3/Eigen/LU:11,
                 from /mnt/sda11/data/Sophus/sophus/so2.hpp:12,
                 from /mnt/sda11/data/Sophus/sophus/rxso2.hpp:7,
                 from /mnt/sda11/data/Sophus/test/core/test_rxso2.cpp:3:
/mnt/sda11/data/Sophus/sophus/rxso2.hpp:604:3: note: because ‘Eigen::Map<Sophus::RxSO2<double> >’ has user-provided ‘Eigen::Map<Sophus::RxSO2<Scalar_>, Options_>& Eigen::Map<Sophus::RxSO2<Scalar_>, Options_>::operator=(const Eigen::Map<Sophus::RxSO2<Scalar_>, Options_>&) [with Scalar_ = double; int Options = 0]’
  604 |   EIGEN_INHERIT_ASSIGNMENT_EQUAL_OPERATOR(Map);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/sda11/data/Sophus/test/core/test_rxso2.cpp: In instantiation of ‘bool Sophus::Tests<Scalar>::testRawDataAcces() [with Scalar = float]’:
/mnt/sda11/data/Sophus/test/core/test_rxso2.cpp:92:15:   required from ‘void Sophus::Tests<Scalar>::runAll() [with Scalar = float]’
/mnt/sda11/data/Sophus/test/core/test_rxso2.cpp:230:25:   required from here
/mnt/sda11/data/Sophus/test/core/test_rxso2.cpp:135:27: error: implicitly-declared ‘Eigen::Map<Sophus::RxSO2<float>, 0, Eigen::Stride<0, 0> >::Map(const Eigen::Map<Sophus::RxSO2<float>, 0, Eigen::Stride<0, 0> >&)’ is deprecated [-Werror=deprecated-copy]
  135 |     Eigen::Map<RxSO2Type> shallow_copy = map_of_rxso2;
      |                           ^~~~~~~~~~~~
In file included from /usr/include/eigen3/Eigen/Core:88,
                 from /usr/include/eigen3/Eigen/LU:11,
                 from /mnt/sda11/data/Sophus/sophus/so2.hpp:12,
                 from /mnt/sda11/data/Sophus/sophus/rxso2.hpp:7,
                 from /mnt/sda11/data/Sophus/test/core/test_rxso2.cpp:3:
/mnt/sda11/data/Sophus/sophus/rxso2.hpp:604:3: note: because ‘Eigen::Map<Sophus::RxSO2<float>, 0, Eigen::Stride<0, 0> >’ has user-provided ‘Eigen::Map<Sophus::RxSO2<Scalar_>, Options_>& Eigen::Map<Sophus::RxSO2<Scalar_>, Options_>::operator=(const Eigen::Map<Sophus::RxSO2<Scalar_>, Options_>&) [with Scalar_ = float; int Options = 0]’
  604 |   EIGEN_INHERIT_ASSIGNMENT_EQUAL_OPERATOR(Map);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/sda11/data/Sophus/test/core/test_rxso2.cpp: In instantiation of ‘bool Sophus::Tests<Scalar>::testRawDataAcces() [with Scalar = ceres::Jet<double, 3>]’:
/mnt/sda11/data/Sophus/test/core/test_rxso2.cpp:92:15:   required from ‘void Sophus::Tests<Scalar>::runAll() [with Scalar = ceres::Jet<double, 3>]’
/mnt/sda11/data/Sophus/test/core/test_rxso2.cpp:234:41:   required from here
/mnt/sda11/data/Sophus/test/core/test_rxso2.cpp:135:27: error: implicitly-declared ‘Eigen::Map<Sophus::RxSO2<ceres::Jet<double, 3> >, 0, Eigen::Stride<0, 0> >::Map(const Eigen::Map<Sophus::RxSO2<ceres::Jet<double, 3> >, 0, Eigen::Stride<0, 0> >&)’ is deprecated [-Werror=deprecated-copy]
  135 |     Eigen::Map<RxSO2Type> shallow_copy = map_of_rxso2;
      |                           ^~~~~~~~~~~~
In file included from /usr/include/eigen3/Eigen/Core:88,
                 from /usr/include/eigen3/Eigen/LU:11,
                 from /mnt/sda11/data/Sophus/sophus/so2.hpp:12,
                 from /mnt/sda11/data/Sophus/sophus/rxso2.hpp:7,
                 from /mnt/sda11/data/Sophus/test/core/test_rxso2.cpp:3:
/mnt/sda11/data/Sophus/sophus/rxso2.hpp:604:3: note: because ‘Eigen::Map<Sophus::RxSO2<ceres::Jet<double, 3> >, 0, Eigen::Stride<0, 0> >’ has user-provided ‘Eigen::Map<Sophus::RxSO2<Scalar_>, Options_>& Eigen::Map<Sophus::RxSO2<Scalar_>, Options_>::operator=(const Eigen::Map<Sophus::RxSO2<Scalar_>, Options_>&) [with Scalar_ = ceres::Jet<double, 3>; int Options = 0]’
  604 |   EIGEN_INHERIT_ASSIGNMENT_EQUAL_OPERATOR(Map);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [test/core/CMakeFiles/test_rxso2.dir/build.make:63: test/core/CMakeFiles/test_rxso2.dir/test_rxso2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:164: test/core/CMakeFiles/test_rxso2.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by johnr14** [comment]
Confirming that it doesn't compile on Fedora 31.
@dougrm can you clone the repository and submit your changes as a pull request, it would be nice :)

**Comment by ibtaylor** [comment]
@dougrm @johnr14 does #242 resolve this for you?
